"""MediaFusion.

Its config is an encrypted string generated by the service, which carries the
user debrid credentials. We never parse it, only forward it.
"""
from ... import settings
from . import stremio

NAME = "mediafusion"
BASE = "https://mediafusion.elfhosted.com"


def search(meta):
    config = settings.get("sources.mediafusion.config", "").strip()
    return stremio.fetch(settings.get("sources.mediafusion.url", BASE),
                         config, meta, NAME)
